NUMBER_NEURON: 6
VOLTAGE_TRESHOLD: 1.0
DELTA: 0.0001
LEARNING_RATE: 0.1
LEAK_RATE: 1.3
TIME_ITERATION: 40
ITERATION_SPIKE_IN: 20


NAME_FILE_REWARD: "/statistics/reward.txt"
NAME_FILE_LEGS: "/statistics/legs.txt"



