NUMBER_NEURON: 6
VOLTAGE_TRESHOLD: 1.0
DELTA: 0.0001
LEARNING_RATE: 0.1
LEAK_RATE: 2.0
TIME_ITERATION: 100.0
ITERATION_SPIKE_IN: 10


NAME_FILE_REWARD: "/statistics/reward.txt"
NAME_FILE_LEGS: "/statistics/legs.txt"



